services:
  interlude-web-client:
    build: .
    ports:
      - "30004:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    container_name: interlude-web-client